using DbFirstApproach.Models;

namespace DbFirstApproach;

public class Program
{
    public static void Main(string[] args)
    {
        // Shift + Right Click in the folder of the project -> Open in Terminal
        // NuGet Package: Microsoft.EntityFrameworkCore.SqlServer.Design
        // dotnet tool install --global dotnet-ef
        // dotnet ef dbcontext scaffold "Server=.;Database=Softuni;Integrated Security=True;TrustServerCertificate=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models
        // Classes are partial because they are generated by the scaffolding process, and we can extend them in separate files without modifying the generated code. This allows us to add custom logic or properties to the classes without risking our changes being overwritten if we regenerate the models from the database.
        // Properties are virtual to enable lazy loading, which allows related entities to be loaded from the database on demand when they are accessed for the first time. This can improve performance by avoiding unnecessary data retrieval until it is actually needed.
        // Properties are overwritten with proxy classes that EF Core generates at runtime to enable features like lazy loading and change tracking. These proxy classes override the virtual properties to add the necessary logic for these features, allowing EF Core to manage the state of the entities effectively.
        var dbContext = new SoftuniContext();
        var employees = dbContext.Employees.ToList();
        foreach (var employee in employees) 
            Console.WriteLine($"{employee.FirstName} {employee.LastName}");
    }
}
